export const styles = String.raw`
*{box-sizing:border-box;letter-spacing:0}html,body{margin:0;padding:0}body{font-family:"PicStatusFont","Microsoft YaHei","PingFang SC","Noto Sans CJK SC",sans-serif;color:var(--text);font-size:20px}
.canvas{width:var(--canvas-width,650px);color:var(--text);background:#3a3a3a;background-image:var(--background);background-position:center;background-size:cover}.mask{padding:16px;background:var(--mask)}.main{display:grid;grid-template-columns:1fr;gap:16px}
.theme-light{--text:#3a3a3a;--muted:#626262;--mask:#fafafa66;--card:#fafafacc;--segment:#b8b8b8;--shadow:2px 2px 6px #4a4a4a66;--gray:#bebebedd;--green:#38a64bcc;--orange:#e9942dcc;--red:#db5b64cc;--blue:#2594c7cc;--purple:#9676cecc;--memory-used:#38a64b;--memory-shared:#9676ce;--memory-compressed:#666d75;--memory-buffers:#2594c7;--memory-cache:#d4aa2a;--memory-free:#c7c7c7;--swap-used:#db5b64;--swap-cache:#d4aa2a}
.theme-dark{--text:#f2f2f2;--muted:#d4d4d4;--mask:#15151588;--card:#262626d9;--segment:#666;--shadow:2px 2px 7px #0009;--gray:#555e;--green:#2b8f45dd;--orange:#b66b20dd;--red:#ae424add;--blue:#207ca5dd;--purple:#7254a6dd;--memory-used:#36a653;--memory-shared:#9a74d0;--memory-compressed:#87909a;--memory-buffers:#3197ca;--memory-cache:#d6b33e;--memory-free:#50545a;--swap-used:#cf535e;--swap-cache:#d6b33e}
.card{border-radius:8px;padding:16px;background:var(--card);box-shadow:var(--shadow);backdrop-filter:blur(3px);overflow:hidden}.no-blur .card{backdrop-filter:none}.no-radius .card,.no-radius .avatar,.no-radius .label,.no-radius .bar,.no-radius .resource-bar{border-radius:0}.no-shadow *{box-shadow:none!important;text-shadow:none!important}
.split>*+*{margin-top:8px;padding-top:8px;border-top:2px solid var(--segment)}.account{display:flex;align-items:center;min-height:88px}.avatar{width:88px;height:88px;flex:0 0 88px;border-radius:50%;object-fit:cover;background:#ffffff66;box-shadow:var(--shadow)}.avatar-fallback{display:flex;align-items:center;justify-content:center;font-size:38px;font-weight:700}.identity{margin-left:12px;min-width:0}.nickname{font-size:28px;font-weight:700;line-height:1.2;overflow-wrap:anywhere}.labels{display:flex;flex-wrap:wrap;gap:3px;margin-top:6px}.label{padding:2px 5px;border-radius:4px;background:var(--gray);color:var(--muted);font-size:16px;box-shadow:var(--shadow)}.label.purple{background:var(--purple)}.label.green{background:var(--green)}.label.blue{background:var(--blue)}.label.orange{background:var(--orange)}.extra{display:grid;grid-template-columns:1fr 1fr;gap:4px}.extra .label{text-align:center}
.donuts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;align-items:start}.donut{text-align:center;min-width:0}.ring{--p:0;--color:var(--green);position:relative;width:min(150px,100%);height:auto;aspect-ratio:1;margin:auto;border-radius:50%;background:conic-gradient(var(--color) calc(var(--p)*1%),var(--gray) 0);box-shadow:var(--shadow)}.ring.segmented{background:var(--ring-gradient)}.ring.medium{--color:var(--orange)}.ring.high{--color:var(--red)}.ring:after{content:"";position:absolute;inset:10%;border-radius:50%;background:var(--card)}.ring-value{position:absolute;inset:0;z-index:1;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:700}.donut-title{font-size:32px;font-weight:700}.donut-caption{min-height:28px;font-size:10px;line-height:1.4;color:var(--muted)}.donut-caption-primary{white-space:pre-line;overflow-wrap:anywhere}.donut-caption-detail{font-size:9px;white-space:nowrap}.memory-details{display:grid;gap:5px;margin-top:10px;padding-top:10px;border-top:2px solid var(--segment)}.resource-row{display:grid;grid-template-columns:38px minmax(0,1fr);gap:7px;align-items:center}.resource-label{font-size:15px;font-weight:700}.resource-bar{position:relative;height:26px;overflow:hidden;border-radius:4px;background:var(--bar-gradient);box-shadow:var(--shadow)}.resource-value{position:absolute;inset:0;display:flex;align-items:center;justify-content:flex-end;padding:0 7px;font-size:13px;font-weight:700;text-shadow:0 0 3px var(--card),0 0 3px var(--card)}
.grid{display:grid;gap:4px;align-items:center}.disk-grid{grid-template-columns:max-content minmax(180px,1fr) 64px;column-gap:8px}.disk-row{display:contents}.bar{height:28px;position:relative;overflow:hidden;border-radius:4px;background:var(--gray);box-shadow:var(--shadow)}.bar-fill{height:100%;background:var(--green)}.bar-fill.medium{background:var(--orange)}.bar-fill.high{background:var(--red)}.bar-text{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:16px}.io-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto auto auto auto;gap:7px}.right{text-align:right}.name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.error{color:#c73543}.empty{text-align:center;color:var(--muted);font-size:16px}.footer{text-align:center;font-size:14px;line-height:1.45;text-shadow:var(--shadow)}
@media(max-width:520px){.donut-caption-detail{font-size:7px}}
`
